### ISSUE TITLE
keymap with "t" not show prefix 

### ISSUE THREAD

**Issue by katinbox** [linty-org/key-menu.nvim#13]
![2022-06-09_09-05](https://user-images.githubusercontent.com/43630437/172749086-d04a7df5-13ff-4cab-8048-3ca62f17624a.png)

**Comment by andmis** [comment]
It looks like you are using a helper function of some sort, called `map`. I suspect that is part of the problem. This issue doesn't reproduce for me:
<img width="437" alt="image" src="https://user-images.githubusercontent.com/5308024/173694365-19297e33-e6e6-4b74-a847-ee51b54668bb.png">

**Comment by katinbox** [comment]
I just define short syntax :(
![2022-06-17_14-15](https://user-images.githubusercontent.com/43630437/174246331-8fba01e7-6567-4e94-b794-851dc3197382.png)

**Comment by andmis** [comment]
Hmm I see. Can you tell me anything else about your configuration? What does the pop-up look like if you just press `<Space>`? Are you running Neovim in a terminal? I noticed that there are other rendering issues in your screenshot -- for example, the horizontal divider line doesn't run the full width -- and I'd like to figure out why.

<img width="178" alt="image" src="https://user-images.githubusercontent.com/5308024/174491094-65e6cdcb-ded1-4b45-8d2d-10cc972bcd6f.png">

**Comment by katinbox** [comment]
![2022-06-25_16-11](https://user-images.githubusercontent.com/43630437/175766757-ef120e4b-31cd-4f1e-8d58-8a7d2c15616d.png)

**Comment by katinbox** [comment]
There're space

**Comment by katinbox** [comment]
local status_ok, keymenu = pcall(require, "key-menu")
if not status_ok then
  return
end

vim.o.timeoutlen = 300
local map = vim.keymap.set
keymenu.set('n', '<Space>')

map('n', '<Space>w', '<Cmd>w<CR>', { desc = 'Save' })
map('n', '<Space>q', '<Cmd>q<CR>', { desc = 'Quit' })
map('n', '<Space>s', '<Cmd>AerialToggle<CR>', { desc = 'Symbols' })

-- You can also pass Lua functions to vim.keymap.set.
local erase_all_lines = function()
  vim.api.nvim_buf_set_lines(0, 0, -1, false, {})
end
map('n', '<Space>k', erase_all_lines, { desc = 'Erase all' })

map('n', '<Space>x', ':bdelete<cr>', { desc = 'Close' })

map('n', '<Space>e', '<cmd>NeoTreeFloat<cr>', { desc = 'Explorer' })

local is_telecope_loaded, _ = pcall(require, "telescope")
if is_telecope_loaded then
  map('n', '<Space>f', function()
    keymenu.open_window('<Space>f')
  end, { desc = 'Telescope' })
  map('n', '<Space>fw', function()
    require("telescope.builtin").live_grep()
  end, { desc = 'Search word' })
  map('n', '<Space>ff', function()
    require("telescope.builtin").find_files()
  end, { desc = 'Search files' })
  map('n', '<Space>fh', function()
    require("telescope.builtin").oldfiles()
  end, { desc = 'Search history' })
  map('n', '<Space>fb', function()
    require("telescope.builtin").buffers()
  end, { desc = 'Search buffers' })
  map('n', '<Space>fs', function()
    local aerial_avail, _ = pcall(require, "aerial")
    if aerial_avail then
      require("telescope").extensions.aerial.aerial()
    else
      require("telescope.builtin").lsp_document_symbols()
    end
  end, { desc = 'Search symbols' })
  map("n", "<Space>fr", function()
    require("telescope.builtin").lsp_references()
  end, { desc = "Search references" })
  map("n", "<Space>fd", function()
    require("telescope.builtin").diagnostics()
  end, { desc = "Search diagnostics" })
end

-- Git
map('n', '<Space>g', function()
  keymenu.open_window('<Space>g')
end, { desc = 'Git' })
map("n", "<Space>gt", function()
  require("telescope.builtin").git_status()
end, { desc = "Git status" })
map("n", "<Space>gb", function()
  require("telescope.builtin").git_branches()
end, { desc = "Git branchs" })
map("n", "<Space>gc", function()
  require("telescope.builtin").git_commits()
end, { desc = "Git commits" })

-- Terminal
local Terminal = require('toggleterm.terminal').Terminal
local toggle_float = function()
  local float = Terminal:new({ direction = "float" })
  return float:toggle()
end
local toggle_lazygit = function()
  local lazygit = Terminal:new({ cmd = 'lazygit', direction = "float" })
  return lazygit:toggle()
end

local toggle_htop = function()
  local htop = Terminal:new({ cmd = 'htop', direction = "float" })
  return htop:toggle()
end

local toggle_node = function()
  local htop = Terminal:new({ cmd = 'node', direction = "float" })
  return htop:toggle()
end

map('n', '<Space>t', function()
  keymenu.open_window('<Space>t')
end, { desc = 'Terminal' })
map('n', '<Space>tt', ':TodoTelescope<cr>', { desc = 'Todo' })
map('n', '<Space>tf', toggle_float, { desc = 'Float' })
map('n', '<Space>tl', toggle_lazygit, { desc = 'LazyGit' })
map('n', '<Space>th', toggle_htop, { desc = 'Htop' })
map('n', '<Space>tn', toggle_node, { desc = 'Node' })

map('n', '<Space>l', function()
  keymenu.open_window('<Space>l')
end, { desc = 'LSP' })
map('n', '<Space>lk', "<cmd>lua vim.lsp.buf.signature_help()<cr>", { desc = 'Help' })
map('n', '<Space>lK', "<cmd>Lspsaga hover_doc<cr>", { desc = 'Docs' })
map('n', '<Space>lw', "<cmd>lua vim.lsp.buf.add_workspace_folder()<cr>", { desc = 'Add workspace' })
map('n', '<Space>lW', "<cmd>lua vim.lsp.buf.remove_workspace_folder()<cr>", { desc = 'Remove workspace' })
map('n', '<Space>ll', "<cmd>lua print(vim.inspect(vim.lsp.buf.list_workspace_folders()))<cr>",
  { desc = 'List workspace' })
map('n', '<Space>lt', "<cmd>lua vim.lsp.buf.type_definition()<cr>", { desc = 'Type definition' })
map('n', '<Space>ld', "<cmd>lua vim.lsp.buf.definition()<cr>", { desc = 'Go To Definition' })
map('n', '<Space>lD', "<cmd>lua vim.lsp.buf.declaration()<cr>", { desc = 'Go To Declaration' })
map('n', '<Space>lr', "<cmd>lua vim.lsp.buf.references()<cr>", { desc = 'References' })
map('n', '<Space>lf', "<cmd>lua vim.lsp.buf.format()<cr>", { desc = 'Format' })
map('n', '<Space>lR', "<cmd>Lspsaga rename<cr>", { desc = 'Rename' })
map('n', '<Space>la', "<cmd>Lspsaga code_action<cr>", { desc = 'Action' })
map('n', '<Space>le', "<cmd>Lspsaga show_line_diagnostics<cr>", { desc = 'Show Line Diagnostic' })
map('n', '<Space>ln', "<cmd>Lspsaga diagnostic_jump_next<cr>", { desc = 'Next Diagnostic' })
map('n', '<Space>lN', "<cmd>Lspsaga diagnostic_jump_prev<cr>", { desc = 'Previous Diagnostic' })
map('n', '<Space>lp', "<cmd>Lspsaga preview_definition<cr>", { desc = 'Preview definition' })
map('n', '<Space>li', "<cmd>LspInfo<cr>", { desc = "LSP information" })
map('n', '<Space>lI', "<cmd>LspInstallInfo<cr>", { desc = 'LSP installer' })

map('n', '<Space>p', function()
  keymenu.open_window('<Space>p')
end, { desc = 'Packer' })
map('n', '<Space>pr', ":PackerClean<cr>", { desc = 'Remove Unused Plugins' })
map('n', '<Space>pc', ":PackerCompile profile=true<cr>", { desc = 'Recompile Plugins' })
map('n', '<Space>pi', ":PackerInstall<cr>", { desc = 'Install Plugins' })
map('n', '<Space>pp', ":PackerProfile<cr>", { desc = 'Packer Profile' })
map('n', '<Space>ps', ":PackerSync<cr>", { desc = 'Sync Plugins' })
map('n', '<Space>pS', ":PackerStatus<cr>", { desc = 'Packer Status' })
map('n', '<Space>pu', ":PackerUpdate<cr>", { desc = 'Update Plugins' })


There my config

**Comment by katinbox** [comment]
Only "t" wrong not working normal :(

**Comment by Shock9616** [comment]
@7ColorsCat did you ever find a solution to this problem? I'm having the same issue with my 'e' bindings

**Comment by 7ColorsCat** [comment]
> @7ColorsCat did you ever find a solution to this problem? I'm having the same issue with my 'e' bindings

Nope.
